import './globals.css'

import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { JetBrains_Mono, Space_Grotesk } from 'next/font/google'
import type { PropsWithChildren } from 'react'

const fontSans = Space_Grotesk({
	subsets: ['latin'],
	variable: '--font-sans',
})

const fontMono = JetBrains_Mono({
	subsets: ['latin'],
	variable: '--font-mono',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang="en" className={cn('h-full antialiased', fontSans.variable, fontMono.variable)}>
			<body className="min-h-full flex flex-col">{children}</body>
		</html>
	)
}
