import './globals.css'

import type { Metadata } from 'next'
import { JetBrains_Mono, Space_Grotesk } from 'next/font/google'
import { PropsWithChildren } from 'react'

const fontSans = Space_Grotesk({
	variable: '--font-sans',
	subsets: ['latin'],
})

const fontMono = JetBrains_Mono({
	variable: '--font-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout(props: PropsWithChildren) {
	const { children } = props

	return (
		<html lang="en" className={`${fontSans.variable} ${fontMono.variable} h-full antialiased`}>
			<body className="min-h-full flex flex-col">{children}</body>
		</html>
	)
}
